# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               California Open Data Reference Book
tagline:             'Tagline'
description:         'Description'
url:                 http://toolkit.cahealthdata.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              California State Library / California Research Bureau
  url:               http://library.ca.gov
  email:             crb@library.ca.gov

# Custom vars
version:             1.0
github:
  repo:           https://github.com/patrick95350/opendata
