# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               California Open Data Reference Book
tagline:             'Tagline'
description:         'Description'
url:                 http://toolkit.cahealthdata.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              California Health Data Project
  url:               https://twitter.com/@CAHealthData
  email:             health@codeforsacramento.org

# Custom vars
version:             1.0
github:
  repo:           https://github.com/CAHealthData/toolkit
