# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               Making Open Data Work in California's State Government
tagline:             'Lessons from Early Adopters'
description:         'Prepared for the California State Library<br /> by the California Research Bureau.'
url:                 http://library.ca.gov/crb/opendatarefbook
baseurl:             'http://castatelibrary.github.io/opendata'
paginate:            5

# About/contact
author:
  name:              California State Library / California Research Bureau
  url:               http://library.ca.gov
  email:             crb@library.ca.gov

# Custom vars
version:             1.0
github:
  repo:           https://github.com/CAStateLibrary/opendata
